CREATE TABLE habits(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    motivation TEXT DEFAULT 'You are doing so well!',
    date_added TIMESTAMPTZ DEFAULT now() NOT NULL,
    goal NUMERIC NOT NULL,
    days_completed INTEGER
);